### ISSUE TITLE
How can we add tests for the Julia side of `GAPJulia`?

### ISSUE THREAD

**Issue by sebasguts** [oscar-system/GAPJulia#102]
I would like to add some tests to the Julia side of `GAPJulia`. The problem is that we need a path to an appropriate GAP executable to start GAP in Julia. So how can we add a portable test setup on the Julia side? Should we use environment variables?

**Comment by fingolfin** [comment]
Well, how do you locally load LibGAP.jl into Julia? For my use, I have a shells script in LibGAP.jl, which starts julia and asks it to execute code like this:
```julia
include("src/initialization.jl")
libgap.run_it("/path/to/gap")
```
So you could do something similar (and also in Travis), just add  third command which runs the tests (e.g. by executing `test/runtests.jl` to follow the Pkg.jl conventions). That script could be generated by a `./configure` script (we run `./configure GAPPATH` for JuliaInterface and JuliaExperimental when building on Travis anyway, might as well add LibGAP.jl).

**Comment by sebasguts** [comment]
Thanks for that suggestion, that is what we will do: Let the script be generated by the configure script!
