### ISSUE TITLE
NewPlist used incorrectly in `to_gap` method

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#119]
The following code creates a plist of capacity `length(v)` but size 0 (!), then fills it, but never sets the length.
```julia
function to_gap(v :: Array{T, 1} where T) :: MPtr
    l = NewPlist(length(v))
    for i in 1:length(v)
        l[i] = v[i]
    end
    return l
end
```

**Comment by sebasguts** [comment]
We need to set it in the `NewPlist`constructor in libgap. See https://github.com/gap-system/gap/pull/2963

**Comment by sebasguts** [comment]
Okay, when investigating this, the list seems to be all right. `[]` uses `ASS_LIST`, so it should set the length correctly:
```
julia> xx=[1]
1-element Array{Int64,1}:
 1

julia> GAP.to_gap(xx)
GAP: [ 1 ]

julia> x = GAP.to_gap(xx)
GAP: [ 1 ]

julia> GAP.GAPFuncs.Length(x)
1
```

**Comment by fingolfin** [comment]
Indeed, I was totally wrong. Sorry!
