### ISSUE TITLE
crash in getproperty for GAPFuncsType

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#122]
Asking for `GAP.GAPFuncs.TRANSDEGREES` segfaults, because `TRANSDEGREES` is an immediate integer, but our code does
```julia
    variable = ccall(:GAP_ValueGlobalVariable,MPtr,(Ptr{UInt8},),name_string)
```
so it expects an MPtr. Return type should instead be a union of MPtr, GapFFE, Int64.

Even with that fixed, that code should still also check that what it got is a function.

**Comment by sebasguts** [comment]
Resolved in #139 by @fingolfin
