### ISSUE TITLE
Various minor issues after conversion to Julia package

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#209]
- [x] the `README.md` file in the root dir is heavily outdated and should be updated
- [x] `etc/gather_coverage.jl` should be updated to fix coverage computation
- [x] remove remaining references to `LibGAP.jl`
- [x] update Travis setup to both test "GAP installed via build.jl", and "GAP installed separately"

**Comment by sebasguts** [comment]
Done in #210 and #211
