### ISSUE TITLE
Avoid underscores `_` as prefix for kernel functions

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#21]
To quote e.g. https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

> In addition to the names documented in this manual, reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and all identifiers regardless of use that begin with either two underscores or an underscore followed by a capital letter are reserved names.

**Comment by fingolfin** [comment]
There is no such convention in the GAP community that I'd know of. I know some example that use a single underscore, but even that's not that common. But that's actually not what I am concerned about here.

Rather, I am talking about the name of *C* function, not the name of the GAP function it implements, and these do not need to match. E.g. in the GAP kernel, the GAP function `Foo` is implemented by `FuncFoo`. If this package followed that pattern, it could also use the `GVAR_FUNC` macro.

**Comment by sebasguts** [comment]
Okay, then we can just use `Func` as prefix. I will change this.

**Comment by sebasguts** [comment]
Fixed.
