### ISSUE TITLE
Consider dropping T_JULIA_FUNC and instead using T_FUNCTION objects with custom handlers

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#26]
Consider these timings, where `myfunc` is a simple Julia function that simply returns its first argument:
```
gap> ListX([1..10^4], [1..2], {i,j} -> i);; time;
14
gap> ListX([1..10^4], [1..2], myfunc);; time;
595
```
So Julia is not competitive at all for function calls.

I think this could be improved by using `T_FUNCTION` objects to wrap Julia functions; this avoids various slow paths in calling the current `T_JULIA_FUNC` objects.

To do this, you need to store the pointer to the julia function somewhere in the `T_FUNCTION`. I think `FEXS_FUNC` should be OK for that. Also set `BODY_FUNC` to zero, so that GAP considers the `T_FUNCTION` object as a kernel handler.

Then rewrite `Func_JuliaCallFunc0Arg` etc. into `DoJuliaCallFunc0Arg` handlers, to be hooked into the various `HDLR_FUNC` slots. I could work on this if you are interested, but I thought I should first find out if there was a reason you haven't used this approach so far.

**Comment by sebasguts** [comment]
There is a small caveat: We started by separating julia functions from objects by `T_JULIA_FUNC` and `T_JULIA_OBJ`, but I am not sure this was the right approach at all (we also dropped it to some extend).

We observed that Julia does not really separate between functions and "callable objects", i.e., objects that have an `()` operator. Can we also install handlers for a `T_JULIA`, unifying the two julia tnums?
