### ISSUE TITLE
Setup Travis (and Codecov?) for this package

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#29]

**Comment by fingolfin** [comment]
The following is based on my memories from a discussion during GAP Days Fall 2018:

The main obstacle for this is that we need a compiled version of Julia with the patch from https://github.com/JuliaLang/julia/pull/28368

@sebasguts wanted to solve this by providing a Docker image with such a Julia in it. Of course that could then also contain a precompiled GAP, Singular, Nemo etc., everything we need. This Docker image could even be added as an "official" download to https://oscar.computeralgebra.de/install/ but then a few things need to be resolved, mostly concerning Julia 0.6 vs. 0.7/1.0 -- as I recall, the main problem there was that Singular.jl is not yet available for Julia 0.7/1.0?

Anyway, having such an image for testing, and then using it to start running serious tests on the packages in this repo, would IMHO be highly desirable.

(And the GAP team could perhaps use it for gap-system/gap to add a test of the Julia GC integration in GAP, just to make sure we don't break it).

**Comment by sebasguts** [comment]
This was resolved by @fingolfin in #59
