### ISSUE TITLE
Revise `ImportJuliaModuleIntoGAP`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#56]
@sebasguts came up with the following plan: the global variable `Julia` will point to a custom GAP object, for which methods for `\.` and `IsBound.` (and possibly `RecNames`) are installed. When accessing `Julia.foobar`, it queries if `Main.foobar` exists; if not, it errors out, otherwise that object is returned.

On the next level, Julia module objects (i.e., `jl_module_t`) are wrapped into custom GAP objects (similar or even identical to the `Julia` object). Then for these the `\.` method of course performs the lookup relative to the `jl_module_t` (in the `Julia` object, this would then be `jl_main_module`).

**Comment by sebasguts** [comment]
This is resolved by #62
