### ISSUE TITLE
JuliaExperimental fails to load when Nemo not present

### ISSUE THREAD

**Issue by sebasguts** [oscar-system/GAPJulia#65]
Currently, there is a `using Nemo` in `utils.jl`, which produced an Error if JuliaExperimental is loaded when using a Julia without Nemo.

Maybe we should split up the `utils.jl` file and load the Nemo specific functions only if Nemo can also be imported into GAP?

**Comment by ThomasBreuer** [comment]
This problem has been solved with pull request #77 .
