### ISSUE TITLE
Implement convenience functions in Julia and in GAP for doing many common basic operations

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAPJulia#79]
It would be very convenient if there were default Julia implementations for `getindex`, `setindex!`, `getproperty`, `setproperty!` that work on any `GapObj` (and raise an error if not applicable).

Here is some untested rough draft (without a working `LibGAP.jl`, it is a bit annoying to work on this)

```julia
# lists
getindex(x::GapObj, i::Int) = GAP.GAPFuncs.ELM_LIST(x, to_gap(i))
setindex!(x::GapObj, v, i::Int) = GAP.GAPFuncs.ASS_LIST(x, to_gap(i), to_gap(v))

# matrix
getindex(x::GapObj, i::Int, j::Int) = GAP.GAPFuncs.ELM_LIST(x, to_gap(i), to_gap(j))
setindex!(x::GapObj, v, i::Int, j::Int) = GAP.GAPFuncs.ASS_LIST(x, to_gap(i), to_gap(j), to_gap(v))

# records
RNamObj(f::Symbol) = GAP.GAPFuncs.RNamObj(to_gap(string(f)))
getproperty(x::GapObj, f::Symbol) = GAP.GAPFuncs.ELM_REC(x, RNamObj(f))
setproperty!(x::GapObj, f::Symbol, v) = GAP.GAPFuncs.ASS_REC(x, RNamObj(f), to_gap(v))
```

**Comment by ThomasBreuer** [comment]
Generic Julia methods would make sense also for `append!`, `push!`, `show` (here we get again the request for a working `ViewString` like feature in GAP),
and also for `=`, `<`, `+`, `-`, `*`, `/`, `^`, `mod`.

**Comment by fingolfin** [comment]
I think @sebasguts added the former, but the latter is still missing (as I just discovered). Also, none of this is being tested right now.

**Comment by fingolfin** [comment]
Another generic method: `string`.

And all of these also should apply for `GapFFE`, too.

**Comment by fingolfin** [comment]
In addition, the converse would also be nice: I.e. to have methods for `\[\]`, `\=`, `\<` etc. in GAP for Julia objects.

**Comment by fingolfin** [comment]
I just noticed that JuliaExperimental provides the latter (GAP helpers to map + to Julia's +, etc.) in its `arith.gi` file. Now I wonder if that shouldn't be moved to `JuliaInterface`?

**Comment by fingolfin** [comment]
We moved the GAP wrappers for Julia arithmetic to `JuliaInterface` in PR #132. So far it is purely on the GAP level. We could of course looking into also doing it via the GAP dispatch tables, though it's not completely clear to me that this would be worth it.
